name    'yakshed-webserver'
version '0.1.0'
source 'UNKNOWN'
author 'Bascht <github.com@bascht.com>'
license 'Apache License, Version 2.0'
summary 'All the yakish webserver stuff'
project_page 'https://github.com/yakshed/puppet-yakshed-webserver'

mod 'puppetlabs/stdlib'
mod 'jfryman/nginx', '0.0.7'
mod 'leoc/piwik'
mod 'nodes/php'