name    'yakshed-webserver'
version '0.1.0'
source 'UNKNOWN'
author 'Bascht <github.com@bascht.com>'
license 'Apache License, Version 2.0'
summary 'All the yakish webserver stuff'
project_page 'https://github.com/yakshed/puppet-yakshed-webserver'

dependency 'puppetlabs/stdlib', '>= 4.4.0'
dependency 'jfryman/nginx', '0.0.7'
dependency 'leoc/piwik', '1.0.0'
dependency 'nodes/php', '0.9.0'